#!/bin/bash

# Config 4: No flag specified. Increase job1 request size to 8 pages

echo "n rqpgs=8 iotype=write qd=1 miwos=8 timebased=1 runtime=30 countbased=0 ss=0 es=4194304 " > /proc/qiog
echo "n rqpgs=8 iotype=write qd=32 miwos=8 timebased=1 runtime=30 countbased=0 ss=4194304 es=8388608" > /proc/qiog
