#!/bin/bash

# Config 9: FUA for job1. Job1.qd=32. Job1.rqpgs=8.

echo "n fua rqpgs=8 iotype=write qd=32 miwos=8 timebased=1 runtime=30 countbased=0 ss=0 es=4194304 " > /proc/qiog
echo "n rqpgs=8 iotype=write qd=32 miwos=8 timebased=1 runtime=30 countbased=0 ss=4194304 es=8388608" > /proc/qiog
